### PR TITLE
multiple players, (blind) carbon copy

### PR DESCRIPTION
**Pull request by PeterNerlich**
rename api, add cc and bcc, handle multiple players
rename: src -> from, dst -> to

*TODO: prevent item duplication from attachments*

### CODE REVIEW

**Comment by PeterNerlich** [comment]
Uhm, are attachments even implemented? On a second look, I only see them mentioned in `api.md`

**Comment by BuckarooBanzay** [comment]
Ok, so i did some testing with the current state and i had some issues starting the even the engine:
```
2020-08-02 14:00:10: [Main]: Automatically selecting world at [/root/.minetest/worlds/world]
2020-08-02 14:00:10: ACTION[Main]: Server: Shutting down
2020-08-02 14:00:10: ERROR[Main]: ModError: Failed to load and run script from /root/.minetest/worlds/world/worldmods/mail_mod/init.lua:
2020-08-02 14:00:10: ERROR[Main]: /root/.minetest/worlds/world/worldmods/mail_mod/gui.lua:226: '}' expected (to close '{' at line 221) near 'subject'
2020-08-02 14:00:10: ERROR[Main]: stack traceback:
2020-08-02 14:00:10: ERROR[Main]: 	[C]: in function 'dofile'
2020-08-02 14:00:10: ERROR[Main]: 	...t/.minetest/worlds/world/worldmods/mail_mod/init.lua:36: in main chunk
```

I fixed various other issues with the code, such as string formatting in the formspec generation and some crashes:
https://github.com/minetest-mail/mail_mod/pull/5/commits/6bf2e5fc416999db6924db076b3c50057149cb53

It still does not work in the current state but i saved my yours and my commits in PR #5

(if this is still a work-in-progress then disregard all the above)

**Comment by PeterNerlich** [comment]
Dived into this again. I think it should work now. I still left the lengthy if statements before the log message in `mail.send()` (`api.lua`), because I expect that to be used by mods and because all the surrounding stuff is already backwards compatible, I don't want a log statement to crash the server when it would have worked otherwise ^^
Also, I saw you rearranged the arguments in some functions to have CC/BCC after TO — I still left them just appended to the end, also to maintain backwards compatibility. If you do not care about that, we can make it nice and consistent everywhere, but I figured if it was this easy it would be a waste to not do it this way.

**Comment by PeterNerlich** [comment]
I reverted the `sender`→`from` rename in storage format because it crashed when reverting to the "old" (official) version. If you are interested in just merging this for now without the stuff in #6, I might look through whether there are some useful changes that belong here and backport those

**Pull request merged**
