### PR TITLE
Contacts

### PR DESCRIPTION
**Pull request by PeterNerlich**
*This PR builds on and thus includes the changes from the updated #4. If this PR is desired to be merged, #4 can be dropped.*

This PR:
- adds multiple player support (see #4)
  - enables sending a mail to multiple players at once (list them comma separated)
  - adds CC and BCC fields when composing a message
  - displays TO and CC fields when viewing a message
- adjusts some GUI elements, mainly in the inbox
- displays messages where the player is only in the CC or BCC fields differently in the inbox
- adds a Reply All button
- adds per player contacts
- adds a contacts GUI to manage contacts (player name + personal notes, renaming supported with collision and empty string prevention)
- adds the automatic creation of contact entries for unknown players in the TO field whenever sending a message
- fixes some minor GUI problems (read/unread display fix, reduce disk writes)

All changes are backwards compatible with mods using the old API. The storage changes do not affect old data, the mod can be downgraded without the loss of any messages.

***EDIT:***

I forgot
- adds contact selection screen (choose contacts to add/remove to TO and CC fields without needing to type them), accessible buttons in compose dialog

When a player joins without having a contacts file, his contacts are initialized by adding all players he received messages from.

### CODE REVIEW

**Comment by BuckarooBanzay** [comment]
> adds per player contacts
> adds a contacts GUI to manage contacts (player name + personal notes, renaming supported with collision and empty string prevention)
> adds the automatic creation of contact entries for unknown players in the TO field whenever sending a message

nice :+1: 

This incorporates all the changes from #4, right? If so: feel free to remove the "draft" marker whenever you are ready and i'll test-drive the whole thing... :boom:  :car:

**Comment by PeterNerlich** [comment]
No, I added the draft thing because I thought something would not be a problem which is turns out not to be true. I assumed `pairs()` might not yield significantly different results over the live span of one lua process if the table stayed the same, but it turns out the order does occasionally change entirely, so now using the contacts is really annoying, especially in the select dialog...

**Comment by PeterNerlich** [comment]
I forgot
- adds contact selection screen (choose contacts to add/remove to TO and CC fields without needing to type them), accessible buttons in compose dialog

When a player joins without having a contacts file, his contacts are initialized by adding all players he received messages from.

**Comment by PeterNerlich** [comment]
Okay, I think this is done now. Here are some screenshots of the new UI:

Inbox:
image

Viewing a message:
image

Composing a message:
image

Selecting recipients:
image

Contacts:
image

Editing a contact:
image

**Comment by PeterNerlich** [comment]
Okay, last thing I wanna do before the merge: Indicate what is TO and what is CC the contact selection dialog

**Comment by PeterNerlich** [comment]
Okay, this is sufficient. Now it looks like this:

image

I don't know why the notes suddenly appear but didn't above. If they don't show for you or if you notice anything weird, let me know.

**Comment by BuckarooBanzay** [comment]
wow, this looks awesome, thanks.
I think the new `cc` and `bcc` fields may have broke the webmail integration but thats up to me :smile:

**Pull request merged**
